jobs:
  include:
    - stage: build
      language: node_js
      dist: xenial
      node_js: '12'
      before_script:
        - sudo apt-get update
        - sudo apt-get install docker-ce
        - npm install -g codecov
        - npm cache clean --force
      script:
        - docker build -t packet_cafe/ui -f ./ui/Dockerfile ./ui
        - docker build -t packet_cafe/ui-test -f ./ui/Dockerfile.test ./ui
    - stage: test
      script:
        - docker run packet_cafe/ui-test 
      after_success:
        - codecov

  include:
    - stage: build
      language: python
      dist: xenial
      python: '3.7'
      before_script:
        - sudo apt-get update
        - sudo apt-get install docker-ce
        - pip install -U pip
        - pip install codecov
      script:
        - docker build -t packet_cafe/web -f ./web/Dockerfile ./web
        - docker build -t packet_cafe/web-test -f ./web/Dockerfile.test ./web
    - stage: test
      script:
        - docker run packet_cafe/web-test
      after_success:
        - codecov