version: '3.7'
services:
  ui:
    restart: always
    build:
      context: ui
      dockerfile: Dockerfile
    image: 'cyberreboot/packet_cafe_ui:latest'
    ports:
      - 5000
    networks:
      - frontend
      - loadbalancer
    deploy:
      replicas: 3
  web:
    restart: always
    build:
      context: web
      dockerfile: Dockerfile
    image: 'cyberreboot/packet_cafe_web:latest'
    networks:
      - frontend
      - loadbalancer
    deploy:
      replicas: 3
  lb:
    restart: always
    build:
      context: lb
      dockerfile: Dockerfile
    image: 'cyberreboot/packet_cafe_lb:latest'
    ports:
      - 80:80
    networks:
      - loadbalancer
  messenger:
    restart: always
    build:
      context: messenger
      dockerfile: Dockerfile
    image: 'cyberreboot/packet_cafe_messenger:latest'
    ports:
      - 15672:15672
    networks:
      - frontend
      - backend
  workers:
    restart: always
    build:
      context: workers
      dockerfile: Dockerfile
    image: 'cyberreboot/packet_cafe_workers:latest'
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 3
networks:
  frontend:
    name: frontend
  backend:
    name: backend
  loadbalancer:
    name: loadbalancer
