version: '3.7'
services:
  networkml:
    image: 'iqtlabs/networkml:v0.6.0'
  pcapplot:
    image: 'iqtlabs/pcapplot:v0.1.7'
  pcap-splitter:
    image: 'iqtlabs/pcap-to-node-pcap:v0.11.15'
  ncapture:
    image: 'iqtlabs/ncapture:v0.11.15'
  pcap-dot1q:
    image: 'iqtlabs/tcprewrite-dot1q:v0.11.15'
  snort:
    image: 'iqtlabs/snort:v0.11.15'
  pcap-stats:
    image: 'iqtlabs/pcap-stats:v0.11.15'
  mercury:
    image: 'iqtlabs/mercury:v0.11.15'
  admin:
    restart: always
    image: 'iqtlabs/packet_cafe_admin:v0.1.0'
    ports:
      - 5001:5001
    networks:
      - admin
    volumes:
      - '${VOL_PREFIX}/files:/files'
      - '${VOL_PREFIX}/id:/id'
  ui:
    restart: always
    image: 'iqtlabs/packet_cafe_ui:v0.1.0'
    networks:
      - frontend
    volumes:
      - '${VOL_PREFIX}/definitions:/definitions'
  web:
    restart: always
    image: 'iqtlabs/packet_cafe_web:v0.1.0'
    networks:
      - frontend
    volumes:
      - '${VOL_PREFIX}/files:/files'
      - '${VOL_PREFIX}/id:/id'
      - '${VOL_PREFIX}/definitions:/definitions'
  lb:
    restart: always
    image: 'iqtlabs/packet_cafe_lb:v0.1.0'
    ports:
      - 80:80
    networks:
      - frontend
      - results
  messenger:
    restart: always
    image: 'iqtlabs/packet_cafe_messenger:v0.1.0'
    networks:
      - frontend
      - backend
      - analysis
      - preprocessing
  redis:
    restart: always
    image: 'iqtlabs/packet_cafe_redis:v0.1.0'
    networks:
      - frontend
      - backend
    volumes:
      - '${VOL_PREFIX}/redis:/data'
  workers:
    restart: always
    image: 'iqtlabs/packet_cafe_workers:v0.1.0'
    networks:
      - backend
      - results
    environment:
      VOL_PREFIX: '${VOL_PREFIX}'
    volumes:
      - '${VOL_PREFIX}/definitions:/definitions'
      - '${VOL_PREFIX}/files:/files'
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  admin:
    name: admin
  frontend:
    name: frontend
  backend:
    name: backend
  analysis:
    name: analysis
  preprocessing:
    name: preprocessing
  results:
    name: results
