version: '3.7'
services:
  networkml:
    image: 'cyberreboot/networkml:v0.5.8'
  pcapplot:
    image: 'cyberreboot/pcapplot:v0.1.6'
  pcap-splitter:
    image: 'cyberreboot/pcap-to-node-pcap:v0.11.12'
  ncapture:
    image: 'cyberreboot/ncapture:v0.11.12'
  pcap-dot1q:
    image: 'cyberreboot/tcprewrite-dot1q:v0.11.12'
  snort:
    image: 'cyberreboot/snort:v0.11.12'
  pcap-stats:
    image: 'cyberreboot/pcap-stats:v0.11.12'
  mercury:
    image: 'cyberreboot/mercury:v0.11.12'
  admin:
    restart: always
    build:
      context: admin
    image: 'cyberreboot/packet_cafe_admin:latest'
    ports:
      - 5001:5001
    networks:
      - admin
    volumes:
      - '${VOL_PREFIX}/files:/files'
      - '${VOL_PREFIX}/id:/id'
  ui:
    restart: always
    build:
      context: ui
    image: 'cyberreboot/packet_cafe_ui:latest'
    networks:
      - frontend
    volumes:
      - '${VOL_PREFIX}/definitions:/definitions'
  web:
    restart: always
    build:
      context: web
    image: 'cyberreboot/packet_cafe_web:latest'
    networks:
      - frontend
    volumes:
      - '${VOL_PREFIX}/files:/files'
      - '${VOL_PREFIX}/id:/id'
      - '${VOL_PREFIX}/definitions:/definitions'
  lb:
    restart: always
    build:
      context: lb
    image: 'cyberreboot/packet_cafe_lb:latest'
    ports:
      - 80:80
    networks:
      - frontend
      - results
  messenger:
    restart: always
    build:
      context: messenger
    image: 'cyberreboot/packet_cafe_messenger:latest'
    networks:
      - frontend
      - backend
      - analysis
      - preprocessing
  redis:
    restart: always
    build:
      context: redis
    image: 'cyberreboot/packet_cafe_redis:latest'
    networks:
      - frontend
      - backend
    volumes:
      - '${VOL_PREFIX}/redis:/data'
  workers:
    restart: always
    build:
      context: workers
    image: 'cyberreboot/packet_cafe_workers:latest'
    networks:
      - backend
      - results
    environment:
      VOL_PREFIX: '${VOL_PREFIX}'
    volumes:
      - '${VOL_PREFIX}/definitions:/definitions'
      - '${VOL_PREFIX}/files:/files'
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  admin:
    name: admin
  frontend:
    name: frontend
  backend:
    name: backend
  analysis:
    name: analysis
  preprocessing:
    name: preprocessing
  results:
    name: results
