version: '3.7'
services:
  networkml:
    image: '${TOOL_NAMESPACE}/networkml:${TOOL_VERSION}'
  pcapplot:
    image: '${TOOL_NAMESPACE}/pcapplot:${TOOL_VERSION}'
  pcap-splitter:
    image: '${TOOL_NAMESPACE}/pcap-to-node-pcap:${TOOL_VERSION}'
  ncapture:
    image: '${TOOL_NAMESPACE}/ncapture:${TOOL_VERSION}'
  pcap-dot1q:
    image: '${TOOL_NAMESPACE}/tcprewrite-dot1q:${TOOL_VERSION}'
  snort:
    image: '${TOOL_NAMESPACE}/snort:${TOOL_VERSION}'
  pcap-stats:
    image: '${TOOL_NAMESPACE}/pcap-stats:${TOOL_VERSION}'
  mercury:
    image: '${TOOL_NAMESPACE}/mercury:${TOOL_VERSION}'
  admin:
    restart: always
    build:
      context: admin
    image: '${SERVICE_NAMESPACE}/packet_cafe_admin:${SERVICE_VERSION}'
    ports:
      - 5001:5001
    networks:
      - admin
    volumes:
      - '${VOL_PREFIX}/files:/files'
      - '${VOL_PREFIX}/id:/id'
  ui:
    restart: always
    build:
      context: ui
    image: '${SERVICE_NAMESPACE}/packet_cafe_ui:${SERVICE_VERSION}'
    networks:
      - frontend
    volumes:
      - '${VOL_PREFIX}/definitions:/definitions'
  web:
    restart: always
    build:
      context: web
    image: '${SERVICE_NAMESPACE}/packet_cafe_web:${SERVICE_VERSION}'
    networks:
      - frontend
    volumes:
      - '${VOL_PREFIX}/files:/files'
      - '${VOL_PREFIX}/id:/id'
      - '${VOL_PREFIX}/definitions:/definitions'
  lb:
    restart: always
    build:
      context: lb
    image: '${SERVICE_NAMESPACE}/packet_cafe_lb:${SERVICE_VERSION}'
    ports:
      - 80:80
    networks:
      - frontend
      - results
  messenger:
    restart: always
    build:
      context: messenger
    image: '${SERVICE_NAMESPACE}/packet_cafe_messenger:${SERVICE_VERSION}'
    networks:
      - frontend
      - backend
      - analysis
      - preprocessing
  redis:
    restart: always
    build:
      context: redis
    image: '${SERVICE_NAMESPACE}/packet_cafe_redis:${SERVICE_VERSION}'
    networks:
      - frontend
      - backend
    volumes:
      - '${VOL_PREFIX}/redis:/data'
  workers:
    restart: always
    build:
      context: workers
    image: '${SERVICE_NAMESPACE}/packet_cafe_workers:${SERVICE_VERSION}'
    networks:
      - backend
      - results
    environment:
      VOL_PREFIX: '${VOL_PREFIX}'
    volumes:
      - '${VOL_PREFIX}/definitions:/definitions'
      - '${VOL_PREFIX}/files:/files'
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  admin:
    name: admin
  frontend:
    name: frontend
  backend:
    name: backend
  analysis:
    name: analysis
  preprocessing:
    name: preprocessing
  results:
    name: results
