name: buildx

on:
  push:
    branches:
      - master
      - develop
    tags: 'v*'

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get version number
      id: get_version
      run: |
        VERSION=$(git describe --tags)
        echo VERSION=${VERSION}
        echo ::set-output name=VERSION::${VERSION}
        TAG_VERSION=$(git describe --abbrev=0 --tags)
        echo TAG_VERSION=${TAG_VERSION}
        echo ::set-output name=TAG_VERSION::${TAG_VERSION}
    - name: Should this workflow push to Docker Hub?
      id: docker
      env:
        DOCKER_PASSWORD:  ${{ secrets.DOCKER_TOKEN }}
        DOCKER_USERNAME:  ${{ secrets.DOCKER_USERNAME }}
      run: |
        PUSH_TO_DOCKER='false'
        if [[ github.event_name == "push" ]] &&
           [[ -n $DOCKER_USERNAME ]] &&
           [[ -n $DOCKER_PASSWORD ]] &&
           [[ ${{ steps.get_version.outputs.VERSION }} == ${{ steps.get_version.outputs.TAG_VERSION }} ]]
        then
          PUSH_TO_DOCKER='true'
        fi
        echo ::set-output name=PUSH_TO_DOCKER::${PUSH_TO_DOCKER}
        echo PUSH_TO_DOCKER=${PUSH_TO_DOCKER}
    - name: Change version for release
      id: change_version
      run: |
        if [ "${GITHUB_REF##*/}" == "master" ]; then
          echo ::set-output name=VERSION::latest;
          echo VERSION=latest
        else
          echo ::set-output name=VERSION::${VERSION};
          echo VERSION=${VERSION}
        fi
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
      if: steps.docker.outputs.PUSH_TO_DOCKER
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: steps.docker.outputs.PUSH_TO_DOCKER
    - name: Build for test only
      run: |
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_admin:${{ steps.change_version.outputs.VERSION }} admin && \
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_ui:${{ steps.change_version.outputs.VERSION }} ui && \
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_web:${{ steps.change_version.outputs.VERSION }} web && \
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_lb:${{ steps.change_version.outputs.VERSION }} lb && \
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_messenger:${{ steps.change_version.outputs.VERSION }} messenger && \
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_redis:${{ steps.change_version.outputs.VERSION }} redis && \
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_workers:${{ steps.change_version.outputs.VERSION }} workers
      if: (! steps.docker.outputs.PUSH_TO_DOCKER)
    - name: Build and push platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_admin:${{ steps.change_version.outputs.VERSION }} admin && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_ui:${{ steps.change_version.outputs.VERSION }} ui && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_web:${{ steps.change_version.outputs.VERSION }} web && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_lb:${{ steps.change_version.outputs.VERSION }} lb && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_messenger:${{ steps.change_version.outputs.VERSION }} messenger && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_redis:${{ steps.change_version.outputs.VERSION }} redis && \
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -t ${{ secrets.DOCKER_USERNAME }}/packet_cafe_workers:${{ steps.change_version.outputs.VERSION }} workers
      if: steps.docker.outputs.PUSH_TO_DOCKER
    - name: List available tags for images
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        for N in admin ui messenger web redis lb workers
        do
          image="${{ secrets.DOCKER_USERNAME }}/packet_cafe_${N}"
          echo "${image}:" $(
            wget -q https://registry.hub.docker.com/v1/repositories/${image}/tags -O - |
              tr -d '[]" ' |
              tr '}' '\n' |
              awk -F: '{printf $3 " "}'
          )
        done
      if: steps.docker.outputs.PUSH_TO_DOCKER
